version: "3.7"

services:
  flask-app:
    restart: always
    stdin_open: true
    hostname: flask-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/flask-app
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DEBUG=1
      - PORT=5002
