version: "3.8"

services:
  neo4j-database:
    image: neo4j:4.4.5-community
    volumes:
      - dbdata:/data
    ports:
      - "7474:7474"
      - "7687:7687"

  flask-app:
    restart: always
    stdin_open: true
    hostname: flask-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/flask-app
    ports:
      - "5002:5002"
    environment:
      FLASK_ENV: development
      DEBUG: 1
      PORT: 5002
      NEO4J_URI: neo4j://neo4j-database:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: test
      JWT_SECRET: "sRwmhGsNXr4Ysy1yWF9D"

volumes:
  dbdata:
