version: "3.7"

services:
  neo4j-database:
    image: neo4j:community
    volumes:
      - dbdata:/data
    ports:
      - "7474:7474"
      - "7687:7687"

  flask-app:
    restart: always
    stdin_open: true
    hostname: flask-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/flask-app
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DEBUG=1
      - PORT=5002
      - NEO4J_URI=neo4j://neo4j-database:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=test

volumes:
  dbdata:
